name: ohms-law
dependencies:
  - bleach
  - bokeh 
  - certifi
  - charset-normalizer
  - idna
  - importlib-metadata
  - Jinja2
  - Markdown
  - MarkupSafe
  - numpy
  - packaging
  - panel
  - param
  - Pillow
  - pyct
  - pyviz-comms
  - PyYAML
  - requests
  - six
  - tornado
  - tqdm
  - typing-extensions
  - urllib3
  - webencodings
  - zipp
