Package            Version  
------------------ ---------
bleach             5.0.1    
bokeh              2.4.3    
certifi            2022.12.7
charset-normalizer 2.1.1    
idna               3.4      
importlib-metadata 5.2.0    
Jinja2             3.1.2    
Markdown           3.4.1    
MarkupSafe         2.1.1    
numpy              1.24.1   
packaging          22.0     
panel              0.14.2   
param              1.12.3   
Pillow             9.3.0    
pip                20.0.2   
pkg-resources      0.0.0    
pyct               0.4.8    
pyviz-comms        2.2.1    
PyYAML             6.0      
requests           2.28.1   
setuptools         44.0.0   
six                1.16.0   
tornado            6.2      
tqdm               4.64.1   
typing-extensions  4.4.0    
urllib3            1.26.13  
webencodings       0.5.1    
zipp               3.11.0   
